version: "3.8"

services:
  client:
    build:
      dockerfile: Dockerfile.dev
    image: eligibility_verification_client:dev
    command: python -m debugpy --wait-for-client --listen 5678 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db